### ISSUE TITLE
Student Project Submission - Predicting Policy Domains and Preferences with BERT and CNN

### ISSUE THREAD

**Issue by allisonkoh** [hertie-data-science-lab/student-projects#1]
Hi, I would like to submit this article by myself and [Daniel Boey](https://github.com/danielboeyks) for the student projects site. This project was developed as part of our coursework for [Natural Language Processing with Deep Learning](https://hertie-data-science-lab.github.io/nlp-deep-learning/) (Spring 2019). 

You can find the materials for our article here: https://github.com/allisonkoh/bertcnn-classifying-manifestos

**Comment by olgasparyan** [comment]
1. I do not know what the norm is, but should the BERT original paper be cited in the intro?
2. I am not sure what is the audience you are targeting with that. If it is only people who know about DL and NLP, then disregard this comment, but if the target is wider - maybe a small glossary of certain terms would be great to provide in the appendix (like what is relu, embeddings or transfer learning and stuff like that). I have seen this done in some polisci papers, but again maybe it is not that important. 
3. In the limitation and analysis section:  Maybe the paragraphs with the topic descriptions should go before the limitations. Or maybe they can go into a separate section? 
4. Gen comment: maybe it will be good to be more consistent with abbreviations. Again, not sure what the norm is, but I would introduce the abbreviations early in the text and then just use them. 
4. Created a PR for some small typos.

**Comment by sjankin** [comment]
Looks good. From my side I am happy with the document as is right now. That would be sufficient for publication on our website. For subsequent submission as a research paper (and depending on the outlet and audience) you might want to revisit @olgasparyan comments 1-3 above. I guess 4&5 from above can be easily fixed before publishing on the website.
